### Get All Jobs

GET http://localhost:8080/api/v1/jobs?

### Get Job Details
GET http://localhost:8080/api/v1/jobs/66fe92f01b03819f9e7caf22

### Get Applicant List
GET http://localhost:8080/api/v1/applicants
