### Get All Jobs

GET http://localhost:8080/api/v1/jobs
### Get Job Details
GET http://localhost:8080/api/v1/jobs/66ff923c464168801739de47

### Get Applicant List
GET http://localhost:8080/api/v1/applicants

### create job
### Create Job
POST http://localhost:8080/api/v1/jobs 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MDIzZmQzMGY5Yjg3YzJiNWY0N2ZlMCIsIm5hbWUiOiIxNDJfU2luZ2dpaCBTZXB0aWFuIE51Z3JhaGEiLCJlbWFpbCI6InNlcHRpYW5zaW5nZ2loOTNAZ21haWwuY29tIiwicGljdHVyZSI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hL0FDZzhvY0xtOWRmMTR2d19SV0ZiV0FGN3VkRXFFMGJieXc0bGhVVWd2UU00U3d0eUNCZUNGQUJYdlE9czk2LWMiLCJyb2xlIjoicmVjcnVpdGVyIiwiaWF0IjoxNzI4MjAwNzA3LCJleHAiOjE3Mjg4MDU1MDd9.eygnqy4CU9bkfhV9NfzfwHFdlA8pz_YITTz2mTAsM1M

{
  "title": "Software Engineer",
  "description": "Develop and maintain web applications.",
  "requiredSkills": ["JavaScript", "React", "Node.js"],
  "experienceLevel": "Mid-level",
  "type": "full_time",
  "placementType": "remote",
  "location": "Remote",
  "companyId": "67023fd30f9b87c2b5f47fe2",  
  "userId": "67023fd30f9b87c2b5f47fe0"   
}








