name: CI/CD Pipeline Virtuosos Job Portal

# akan dijalankan ketika push ke branch main
on:
  push:
    branches:
      - main

# hal yang dijalankan
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Logging
        run: echo "Start deploy to production..."
      
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Setup Bun.js
        run: |
          if ! command -v bun &> /dev/null
          then
            curl -fsSL https://bun.sh/install | bash
          fi
          export BUN_INSTALL="$HOME/.bun"
          export PATH="$BUN_INSTALL/bin:$PATH"
          bun --version

          if ! command -v pnpm &> /dev/null
          then
            npm install -g pnpm
          fi
          pnpm --version
      
      - name: Build Docker Image
        run: docker build -t indraarianggi/virtuosos-jobportal .
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Push Docker Image to Docker Hub
        run: docker push indraarianggi/virtuosos-jobportal
      
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            docker pull indraarianggi/virtuosos-jobportal
            docker stop virtuosos-jobportal || true
            docker rm virtuosos-jobportal || true
            docker run -d --name virtuosos-jobportal -p 8080:8080 indraarianggi/virtuosos-jobportal
