name: CI/CD Pipeline Virtuosos Job Portal

# akan dijalankan ketika push ke branch main
on:
  push:
    branches:
      - main

# hal yang dijalankan
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Logging
        run: echo "Start deploy to production..."
      
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        run: |
          npm install -g pnpm@latest
          pnpm install
      
      - name: Build Docker Image
        run: docker build -t indraarianggi/virtuosos-jobportal .
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Push Docker Image to Docker Hub
        run: docker push indraarianggi/virtuosos-jobportal
      
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            docker pull indraarianggi/virtuosos-jobportal
            docker stop virtuosos-jobportal || true
            docker rm virtuosos-jobportal || true
            docker run -d --name virtuosos-jobportal -p 8080:8080 \
              -e PORT=${{ secrets.PORT }} \
              -e GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
              -e GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} \
              -e GOOGLE_REDIRECT_URL=${{ secrets.GOOGLE_REDIRECT_URL }} \
              -e MONGO_URI=${{ secrets.MONGO_URI }} \
              -e ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }} \
              -e REFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }} \
              -e ACCESS_TOKEN_EXPIRES_TIME=${{ secrets.ACCESS_TOKEN_EXPIRES_TIME }} \
              -e REFRESH_TOKEN_EXPIRES_TIME=${{ secrets.REFRESH_TOKEN_EXPIRES_TIME }} \
              -e CLIENT_URL=${{ secrets.CLIENT_URL }} \
              -e CLIENT_AUTH_SUCCESS_REDIRECT_URL=${{ secrets.CLIENT_AUTH_SUCCESS_REDIRECT_URL }} \
              -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
              indraarianggi/virtuosos-jobportal
